### ISSUE TITLE
power_assert 3.0.0 doesn't work on Ruby 2.5-3.0

### ISSUE THREAD

**Issue by kou** [test-unit/test-unit#330]
See https://github.com/test-unit/test-unit/actions/runs/18800855568/job/54336754086 :

```text
Your RubyGems version (2.7.6.3) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
/opt/hostedtoolcache/Ruby/2.5.9/x64/bin/ruby test/run.rb
/opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/power_assert-3.0.0/lib/power_assert/parser.rb:146: warning: else without rescue is useless
/home/runner/work/test-unit/test-unit/lib/test/unit/util/backtracefilter.rb:16:in `method': undefined method `start' for class `#<Class:PowerAssert>' (NameError)
	from /home/runner/work/test-unit/test-unit/lib/test/unit/util/backtracefilter.rb:16:in `<module:BacktraceFilter>'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/util/backtracefilter.rb:9:in `<module:Util>'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/util/backtracefilter.rb:8:in `<module:Unit>'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/util/backtracefilter.rb:7:in `<module:Test>'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/util/backtracefilter.rb:6:in `<top (required)>'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/assertions.rb:7:in `require_relative'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/assertions.rb:7:in `<top (required)>'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/testcase.rb:12:in `require_relative'
	from /home/runner/work/test-unit/test-unit/lib/test/unit/testcase.rb:12:in `<top (required)>'
	from /home/runner/work/test-unit/test-unit/lib/test/unit.rb:3:in `require_relative'
	from /home/runner/work/test-unit/test-unit/lib/test/unit.rb:3:in `<top (required)>'
	from test/run.rb:19:in `require'
	from test/run.rb:19:in `<main>'
rake aborted!
Command failed with status (1): [/opt/hostedtoolcache/Ruby/2.5.9/x64/bin/ruby test/run.rb]
/home/runner/work/test-unit/test-unit/Rakefile:52:in `block in <top (required)>'
/opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```
