### ISSUE TITLE
Ruby : What changes needed to make test-unit-1.2.3 working with Ruby-2.4.1

### ISSUE THREAD

**Issue by tarun2492** [test-unit/test-unit#148]
I am new to Ruby Development. Now i am working on ruby test-framework code which was working fine with Ruby-1.8.7 Now i want to upgrade ruby [Ruby-2.4.1] for this framework. I have found that test-unit-1.2.3 is included in Ruby-1.8.7 so i have installed it separately with Ruby-2.4.1. Currently i am facing method missing issue ["register_autorunner"] with this combination.

Below is the error : 
_undefined method `register_runner' for Test::Unit::AutoRunner:Class_

I am  including test-unit gem in following way : 
_gem "test-unit","1.2.3"
require "test/unit"_

I am having two questions here, 

1. Is test-unit1.2.3 is fully compatible with Ruby-2.4.1 ?

 2 If it is compatible then what are changes needed to be done in this case

**Comment by kou** [comment]
Please show a program that reproduces the problem.
